# Generated by Django 4.2.1 on 2023-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=30, verbose_name='작성자')),
                ('title', models.TextField(verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
            ],
        ),
    ]
